[project]
name = "nfl-dashboard"
version = "0.1.0"
requires-python = ">=3.11"

dependencies = [
    "polars",
    "numba",
    "pandas",
    "matplotlib",
    "fastapi",
    "grafanalib",
    "jupyterlab",
]
